<a href="https://colab.research.google.com/github/zjzsu2000/CMPE258/blob/master/Ungraded_assignment_4/Ungraded_assignment4__chapter2_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Tensor Fundamentals

In [0]:
import torch

In [2]:
torch.version.__version__

'1.5.0+cu101'

In [0]:
a = torch.ones(3,3)

In [5]:
print(a)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [0]:
a = torch.ones(2,3)

In [7]:
print(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [0]:
a = torch.empty(2,4)

In [9]:
torch.ones_like(a)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [0]:
a[1] = 3

In [11]:
torch.ones_like(a)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [13]:
print(a)


tensor([[1.7495e-37, 0.0000e+00, 3.3631e-44, 0.0000e+00],
        [3.0000e+00, 3.0000e+00, 3.0000e+00, 3.0000e+00]])


In [0]:
b = torch.ones(2,4)

In [15]:
a + b

tensor([[1., 1., 1., 1.],
        [4., 4., 4., 4.]])

In [0]:
points = torch.tensor([[1.0, 4.0], [2.0, 5.0], [3.0, 6.0]])

In [24]:
points.shape

torch.Size([3, 2])

In [25]:
print(points)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


##2.2 Access Elements

In [26]:
points[0, 1]

tensor(4.)

In [27]:
points[0]

tensor([1., 4.])

In [28]:
points[2]

tensor([3., 6.])

In [29]:
points[2,1]

tensor(6.)

## 2.3 Size, storage offset, and strides

###  Storage of Tensors

In [30]:
points.storage()

 1.0
 4.0
 2.0
 5.0
 3.0
 6.0
[torch.FloatStorage of size 6]

Index storage Manually

In [31]:
points_storage = points.storage()
points_storage[0]

1.0

In [32]:
points.storage()[1]

4.0

In [33]:
points.storage()[5]

6.0

In [36]:
points[1]

tensor([2., 5.])

In [37]:
second_point = points[1]
second_point.storage_offset()

2

In [38]:
second_point.size()

torch.Size([2])

### Stride ,offset

In [40]:
points.stride()

(2, 1)

In [41]:
second_point.storage_offset()

2

In [42]:
second_point.stride()

(1,)

### Change subTensor will affect the Original tensors

In [43]:
points

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [44]:
second_point

tensor([2., 5.])

In [0]:
second_point[0] = 10.0

In [46]:
second_point

tensor([10.,  5.])

In [47]:
points

tensor([[ 1.,  4.],
        [10.,  5.],
        [ 3.,  6.]])

### Clone Subtensor, which will not change original Tensor

In [0]:
points = torch.tensor([[1.0, 4.0], [2.0, 5.0], [3.0, 6.0]])
second_point = points[1].clone()


In [51]:
second_point[0] = 10.0
points

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

##Transpose

In [0]:
points_transpose = points.t()

In [53]:
points_transpose

tensor([[1., 2., 3.],
        [4., 5., 6.]])

### Points and Points Transpose share the Storage

In [55]:
id(points.storage()) == id(points_transpose.storage())

True

### Points and Points Transpose differe in shape and Stride

In [56]:
points.stride()

(2, 1)

In [57]:
points_transpose.stride()

(1, 2)

In [59]:
points.shape

torch.Size([3, 2])

In [61]:
points_transpose.shape

torch.Size([2, 3])

## 2.4 Numerical Types

In [0]:
double_points = torch.ones(10, 2, dtype=torch.double)

In [0]:
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

In [64]:
double_points.dtype

torch.float64

In [65]:
short_points.dtype

torch.int16

### Cast dtypes

In [0]:
double_points = torch.zeros(10, 2).double()

In [67]:
double_points.dtype

torch.float64

In [0]:
shourt_points = torch.zeros(10, 2).short()

In [76]:
shourt_points.dtype

torch.int16

In [0]:
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)

In [80]:
double_points.dtype


torch.float64

In [81]:
shourt_points.dtype

torch.int16

In [0]:
points = torch.randn(10, 2) # randn initializes the tensor elements to random numbers between 0 and 1.
short_points = points.type(torch.short)

In [83]:
short_points

tensor([[ 2,  0],
        [ 0,  1],
        [ 0,  0],
        [ 1,  0],
        [ 0,  0],
        [ 0,  0],
        [ 0,  2],
        [-1,  0],
        [ 0,  1],
        [ 0,  2]], dtype=torch.int16)

## 2.5 Indexing **tensors**

In [96]:
#list
some_list = list(range(6))
print(some_list) 
print(some_list[:]) #all
print(some_list[1:4]) # From element 1 inclusive to element 4 exclusive 
print(some_list[1:]) # From element 1 inclusive to the end of the list
print(some_list[:4]) # From the start of the list to element 4 exclusive
print(some_list[:-1]) # From the start of the list to to element 4 exclusive one before the last element
print(some_list[1:4:2]) # From element 1 inclusive to element 4 exclusive in steps of 2

[0, 1, 2, 3, 4, 5]
[0, 1, 2, 3, 4, 5]
[1, 2, 3]
[1, 2, 3, 4, 5]
[0, 1, 2, 3]
[0, 1, 2, 3, 4]
[1, 3]


To achieve your goal, you can use the same notation for PyTorch tensors, with the added benefit that as in NumPy and in other Python scientific libraries, we can use range indexing for each dimension of the tensor:

In [93]:
#tensor
#All rows after first, implicitly all columns
points[1:] 


tensor([[ 0.5842,  1.7409],
        [-0.2202,  0.4330],
        [ 1.0882,  0.7176],
        [ 0.3518, -0.1499],
        [ 0.7377, -0.5782],
        [-0.1283,  2.3164],
        [-1.0313,  0.8476],
        [-0.6358,  1.2805],
        [-0.5836,  2.1517]])

In [94]:
#All rows All rows after first, implicitly all columns after first,all columns
points[1:, :]

tensor([[ 0.5842,  1.7409],
        [-0.2202,  0.4330],
        [ 1.0882,  0.7176],
        [ 0.3518, -0.1499],
        [ 0.7377, -0.5782],
        [-0.1283,  2.3164],
        [-1.0313,  0.8476],
        [-0.6358,  1.2805],
        [-0.5836,  2.1517]])

In [95]:
#All rows after first, first column
points[1:, 0]

tensor([ 0.5842, -0.2202,  1.0882,  0.3518,  0.7377, -0.1283, -1.0313, -0.6358,
        -0.5836])

In addition to using ranges, PyTorch features a powerful form of indexing called advanced indexing.

## 2.6 NumPy interoperability

In [0]:
points = torch.ones(4, 5)

In [0]:
points_np = points.numpy()

In [110]:
points_np

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)

### Convert NumPy array to PyTorch tensor

In [0]:
points = torch.from_numpy(points_np)

In [112]:
points

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

## 2.7 Serializing tensors

save your points tensor
to a ourpoints.t file:
#

In [98]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
root_dir = '/content/drive/My Drive/'
base_dir = root_dir + 'CMPE258/assignment/'
data_dir_me=base_dir+'data/'

In [0]:
with open(data_dir_me+'ourpoints.t','wb') as f:
  torch.save(points, f)


Loading your points back

In [0]:
points = torch.load(data_dir_me+'ourpoints.t')

In [115]:
points

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [0]:
with open(data_dir_me+'ourpoints.t','rb') as f:
  points = torch.load(f)  

In [119]:
points

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

Use the HDF5 format and library.
HDF5 is a portable, widely supported format for representing serialized multidimensional arrays, organized in a nested key-value dictionary. Python supports HDF5 through the h5py library7, which accepts and returns data under the form of NumPy arrays.

In [123]:
!pip install h5py

In [0]:
import h5py

In [0]:
f = h5py.File(data_dir_me+'ourpoints.hdf5', 'w')
dset = f.create_dataset('coords', data=points.numpy())
f.close()

Here, 'coords' is a key into the HDF5 file. You can have other keys, even nested ones.
One interesting thing in HDF5 is that you can index the data set while on disk and access only the elements you’re interested in. Suppose that you want to load only the last two points in your data set:

In [127]:
f = h5py.File(data_dir_me+'ourpoints.hdf5', 'r')
dset = f['coords']
dset

<HDF5 dataset "coords": shape (4, 5), type "<f4">

In [0]:
last_points = dset[1:]

In [129]:
last_points

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)

In [0]:
last_points = torch.from_numpy(dset[1:])
f.close()# When you finish loading data, close the file

In [131]:
last_points

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

## 2.8 Moving tensors to the GPU

One last point about PyTorch tensors is related to computing on the GPU. Every Torch tensor can be transferred to a GPUs to perform fast, massively parallel computations.All operations to be performed on the tensor are carried out by GPU-specific routines that come with PyTorch.



In [0]:
points_gpu = torch.tensor([[1.0, 4.0], [2.0, 5.0], [3.0, 6.0]],
device='cuda')

In [136]:
points_gpu

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]], device='cuda:0')

OR

In [0]:
points_gpu = points.to(device='cuda')

In [138]:
points_gpu

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], device='cuda:0')

This code returns a new tensor that has the same numerical data but is stored in the RAM of the GPU rather than in regular system RAM.

In case your machine has more than one GPU, you can decide which GPU to allocate
the tensor to by passing a zero-based integer identifying the GPU on the
machine:

In [142]:
points_gpu = points.to(device='cuda:0')
points_gpu

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], device='cuda:0')

In [0]:
points = 2 * points #performed on the CPU


In [0]:
points_gpu = 2 * points.to(device='cuda') #performed on the GPU

In [0]:
points_gpu = points_gpu + 4 #performed on the GPU

To move the tensor back to the
CPU, you need to provide a cpu argument to the to method:

In [0]:
points_cpu = points_gpu.to(device='cpu')

In [152]:
#shorthand methods cpu and cuda instead of the to method to achieve the same goal

points_gpu = points.cuda()
points_gpu

tensor([[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]], device='cuda:0')

In [153]:
points_gpu = points.cuda(0)
points_gpu

tensor([[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]], device='cuda:0')

In [156]:
points_cpu = points_gpu.cpu()
points_cpu


tensor([[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]])

when you use the to method, you can change the placement
and the data type simultaneously by providing device and dtype as arguments.


## 2.9 The tensor API
http://pytorch.org/docs.

In [159]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)
print(a)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [160]:
a_t

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [0]:
a = torch.ones(3, 2)
a_t = a.transpose(0, 1)

In [162]:
a_t

tensor([[1., 1., 1.],
        [1., 1., 1.]])

No difference exists between the two forms, which can be used interchangeably.
A caveat, though: a small number of operations exist only as methods of the tensor object. They’re recognizable by the trailing underscore in their name, such as zero_, which indicates that the method operates in-place by modifying the input instead of creating a new output tensor and returning it. The zero_ method, for example, zeros out all the elements of the input. Any method without the trailing underscore leaves the source tensor unchanged and returns a new tensor:

In [163]:
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

# Exercises

## Create a tensor a from list(range(9)). Predict then check what the size, offset,and strides are.

In [170]:
a=list(range(9))
a


[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [0]:
ponits=torch.tensor(a)

In [178]:
ponits

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [186]:
ponits.shape

torch.Size([9])

In [183]:
ponits.storage_offset()

0

In [185]:
ponits.stride()

(1,)

## Create a tensor b = a.view(3, 3). What is the value of b[1,1]?

In [0]:
points2 = ponits.view(3,3)

In [199]:
points2

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [200]:
points2[1,1]

tensor(4)

## Create a tensor c = b[1:,1:]. Predict then check what the size, offset, and strides are.

In [0]:
c=points2[1:,1:]

In [202]:
c

tensor([[4, 5],
        [7, 8]])

In [203]:
c.shape

torch.Size([2, 2])

In [204]:
c.storage_offset()

4

In [205]:
c.stride()

(3, 1)

## Pick a mathematical operation like cosine or square root. Can you find a corresponding function in the torch library?

[res] torch.cos([res,] x)

y=torch.cos(x) returns a new tensor with the cosine of the elements of x.

x:cos() replaces all elements in-place with the cosine of the elements of x.

In [0]:
k = torch.rand(10,10)
d=torch.cos(k)

In [220]:
k

tensor([[0.7858, 0.1320, 0.2265, 0.4890, 0.8511, 0.4676, 0.5435, 0.5065, 0.5492,
         0.2659],
        [0.8580, 0.2166, 0.8840, 0.0196, 0.2575, 0.4717, 0.2190, 0.1386, 0.5936,
         0.6763],
        [0.9547, 0.9802, 0.0292, 0.1925, 0.6326, 0.2736, 0.8223, 0.9924, 0.5018,
         0.4749],
        [0.3358, 0.7169, 0.8469, 0.1960, 0.1983, 0.3658, 0.0315, 0.9224, 0.0783,
         0.6227],
        [0.6558, 0.4957, 0.0566, 0.7787, 0.2124, 0.7790, 0.2243, 0.5502, 0.9781,
         0.5971],
        [0.6237, 0.7794, 0.7465, 0.8335, 0.3850, 0.2958, 0.7079, 0.6305, 0.9680,
         0.5526],
        [0.8008, 0.6798, 0.3953, 0.8892, 0.2845, 0.2776, 0.8628, 0.0524, 0.1132,
         0.0334],
        [0.3806, 0.8995, 0.5047, 0.2532, 0.3131, 0.2261, 0.4299, 0.0818, 0.7824,
         0.4470],
        [0.5383, 0.7300, 0.0617, 0.1534, 0.6065, 0.3729, 0.7372, 0.8177, 0.1181,
         0.3043],
        [0.4366, 0.5531, 0.8415, 0.8917, 0.7501, 0.7207, 0.8232, 0.0431, 0.9507,
         0.9690]])

In [221]:
d

tensor([[0.7068, 0.9913, 0.9745, 0.8828, 0.6592, 0.8926, 0.8559, 0.8745, 0.8529,
         0.9648],
        [0.6540, 0.9766, 0.6340, 0.9998, 0.9670, 0.8908, 0.9761, 0.9904, 0.8289,
         0.7799],
        [0.5779, 0.5569, 0.9996, 0.9815, 0.8065, 0.9628, 0.6805, 0.5467, 0.8767,
         0.8893],
        [0.9441, 0.7539, 0.6623, 0.9809, 0.9804, 0.9338, 0.9995, 0.6039, 0.9969,
         0.8123],
        [0.7926, 0.8796, 0.9984, 0.7118, 0.9775, 0.7116, 0.9749, 0.8524, 0.5586,
         0.8270],
        [0.8117, 0.7114, 0.7341, 0.6723, 0.9268, 0.9566, 0.7597, 0.8077, 0.5669,
         0.8512],
        [0.6961, 0.7777, 0.9229, 0.6301, 0.9598, 0.9617, 0.6503, 0.9986, 0.9936,
         0.9994],
        [0.9285, 0.6220, 0.8753, 0.9681, 0.9514, 0.9745, 0.9090, 0.9967, 0.7092,
         0.9017],
        [0.8586, 0.7452, 0.9981, 0.9883, 0.8217, 0.9313, 0.7403, 0.6839, 0.9930,
         0.9541],
        [0.9062, 0.8509, 0.6663, 0.6281, 0.7316, 0.7513, 0.6799, 0.9991, 0.5812,
         0.5662]])

square root.

[res] torch.sqrt([res,] x)

y=torch.sqrt(x) returns a new tensor with the square root of the elements of x.

x:sqrt() replaces all elements in-place with the square root of the elements of x.

In [0]:
e = torch.sqrt(k)

In [223]:
e

tensor([[0.8864, 0.3634, 0.4759, 0.6993, 0.9225, 0.6838, 0.7372, 0.7117, 0.7411,
         0.5157],
        [0.9263, 0.4654, 0.9402, 0.1400, 0.5075, 0.6868, 0.4680, 0.3724, 0.7705,
         0.8224],
        [0.9771, 0.9900, 0.1709, 0.4387, 0.7954, 0.5230, 0.9068, 0.9962, 0.7084,
         0.6891],
        [0.5795, 0.8467, 0.9203, 0.4427, 0.4453, 0.6048, 0.1774, 0.9604, 0.2798,
         0.7891],
        [0.8098, 0.7041, 0.2379, 0.8824, 0.4609, 0.8826, 0.4737, 0.7418, 0.9890,
         0.7727],
        [0.7898, 0.8828, 0.8640, 0.9130, 0.6204, 0.5438, 0.8414, 0.7940, 0.9839,
         0.7434],
        [0.8949, 0.8245, 0.6287, 0.9430, 0.5334, 0.5269, 0.9289, 0.2289, 0.3365,
         0.1828],
        [0.6169, 0.9484, 0.7104, 0.5032, 0.5596, 0.4755, 0.6557, 0.2860, 0.8845,
         0.6686],
        [0.7337, 0.8544, 0.2485, 0.3916, 0.7788, 0.6107, 0.8586, 0.9043, 0.3437,
         0.5516],
        [0.6608, 0.7437, 0.9173, 0.9443, 0.8661, 0.8490, 0.9073, 0.2076, 0.9750,
         0.9844]])

## function that operates in-place

In [230]:
k.cos_()

tensor([[0.7068, 0.9913, 0.9745, 0.8828, 0.6592, 0.8926, 0.8559, 0.8745, 0.8529,
         0.9648],
        [0.6540, 0.9766, 0.6340, 0.9998, 0.9670, 0.8908, 0.9761, 0.9904, 0.8289,
         0.7799],
        [0.5779, 0.5569, 0.9996, 0.9815, 0.8065, 0.9628, 0.6805, 0.5467, 0.8767,
         0.8893],
        [0.9441, 0.7539, 0.6623, 0.9809, 0.9804, 0.9338, 0.9995, 0.6039, 0.9969,
         0.8123],
        [0.7926, 0.8796, 0.9984, 0.7118, 0.9775, 0.7116, 0.9749, 0.8524, 0.5586,
         0.8270],
        [0.8117, 0.7114, 0.7341, 0.6723, 0.9268, 0.9566, 0.7597, 0.8077, 0.5669,
         0.8512],
        [0.6961, 0.7777, 0.9229, 0.6301, 0.9598, 0.9617, 0.6503, 0.9986, 0.9936,
         0.9994],
        [0.9285, 0.6220, 0.8753, 0.9681, 0.9514, 0.9745, 0.9090, 0.9967, 0.7092,
         0.9017],
        [0.8586, 0.7452, 0.9981, 0.9883, 0.8217, 0.9313, 0.7403, 0.6839, 0.9930,
         0.9541],
        [0.9062, 0.8509, 0.6663, 0.6281, 0.7316, 0.7513, 0.6799, 0.9991, 0.5812,
         0.5662]])

In [231]:
k.sqrt_()

tensor([[0.8407, 0.9956, 0.9871, 0.9396, 0.8119, 0.9448, 0.9252, 0.9351, 0.9235,
         0.9823],
        [0.8087, 0.9883, 0.7963, 0.9999, 0.9834, 0.9438, 0.9880, 0.9952, 0.9104,
         0.8831],
        [0.7602, 0.7462, 0.9998, 0.9907, 0.8980, 0.9812, 0.8249, 0.7394, 0.9363,
         0.9430],
        [0.9717, 0.8683, 0.8138, 0.9904, 0.9902, 0.9664, 0.9998, 0.7771, 0.9985,
         0.9013],
        [0.8903, 0.9379, 0.9992, 0.8437, 0.9887, 0.8436, 0.9874, 0.9233, 0.7474,
         0.9094],
        [0.9009, 0.8434, 0.8568, 0.8199, 0.9627, 0.9780, 0.8716, 0.8987, 0.7529,
         0.9226],
        [0.8343, 0.8819, 0.9607, 0.7938, 0.9797, 0.9807, 0.8064, 0.9993, 0.9968,
         0.9997],
        [0.9636, 0.7887, 0.9356, 0.9839, 0.9754, 0.9872, 0.9534, 0.9983, 0.8422,
         0.9496],
        [0.9266, 0.8632, 0.9990, 0.9941, 0.9065, 0.9650, 0.8604, 0.8270, 0.9965,
         0.9768],
        [0.9519, 0.9224, 0.8163, 0.7925, 0.8554, 0.8668, 0.8245, 0.9995, 0.7623,
         0.7524]])